---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-bionic
    image: ubuntu:18.04
    pull: true
    env:
      MYSQL_ROOT_PASSWORD: "SomethingSecure123!"
      MYSQL_TCP_PORT: "3306"
      NODE_ENV: "development"
      NOTEJAM_PORT: "3000"
      NOTEJAM_VERSION: "0.0.1"
      TF_VAR_mysql_root_password: "SomethingSecure123!"
      TF_VAR_mysql_tcp_port: "3306"
      TF_VAR_node_env: "development"
      TF_VAR_notejam_port: "3000"
      TF_VAR_notejam_version: "0.0.1"
      TF_VAR_ssh_key_name: "notejam"
    restart_policy: on-failure
    restart_retries: 1
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: root
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
